zeromin41/YumNyang

src/constants/options.js, src/layout/AuthLayout.jsx, src/layout/AuthLayout.module.css, src/pages/SignUpPage.jsx, src/pages/SignUpPage.module.css, src/routes/index.jsx
=> 회원가입 페이지 레이아웃 및 스타일링

src/Default.module.css, src/components/Header.module.css, src/components/Menu.module.css, src/index.css
=> 화면 레이아웃 및 스타일링

src/components/Menu.module.css
=> Fix: 하단바 메뉴가 뷰포트 기준으로 밀리는 문제 수정

src/apis/auth.js, src/components/Button.jsx, src/components/Button.module.css, src/pages/SignUpPage.jsx
- 회원가입 이름, 닉네임 중복 확인 API 작성 및 연동
=> 회원가입 이름, 닉네임 중복 확인

src/apis/auth.js, src/pages/SignUpPage.jsx
=> 회원가입 API 연동

src/apis/api.js, src/apis/auth.js, src/constants/initialStates.js, src/pages/LoginPage.jsx, src/pages/SignUpPage.jsx
=> 로그인 API 연동

src/apis/api.js, src/apis/auth.js, src/pages/LoginPage.jsx, src/pages/WithdrawPage.jsx
=> 회원탈퇴 API 연동

src/apis/api.js, src/apis/auth.js, src/pages/WithdrawPage.jsx, src/utils/apiConfig.js
=> Fix: 회원 토큰 확인 로직 수정

src/Default.module.css, src/components/Header.jsx, src/components/Menu.jsx, src/components/RecipeCardSkeleton.jsx, src/components/RecipeCardSwiper.jsx, src/pages/MyPage.jsx, src/pages/MyPage.module.css, src/routes/index.jsx
=> 마이페이지 레이아웃 및 스타일링 작업

src/apis/myPage.js, src/components/Button.module.css, src/components/DropDown.jsx, src/components/Input.jsx, src/components/Input.module.css, src/components/UserEditForm.jsx, src/components/UserEditForm.module.css, src/pages/MyPage.jsx, src/pages/MyPage.module.css, src/pages/SignUpPage.jsx, src/utils/validator.js
=> 마이페이지 레이아웃 작업 및 정보 수정 기능 구현

src/components/SplashScreen.jsx, src/components/SplashScreen.module.css, src/main.jsx
스플래쉬 컴포넌트 추가 후 메인페이지와 연동 (새로고침시 보임)
=> Feat:스플래쉬 페이지 추가

package.json, src/mocks/recipes.js, src/pages/MyPage.jsx, src/store/favoritesSlice.js
=> 마이페이지 찜한 레시피 조회 기능 구현

src/components/RecipeCardSwiper.jsx, src/pages/MyPage.jsx, src/utils/mappingData.js
- 내가 작성한 리뷰 데이터
- 내가 작성한 레시비 데이터
=> 마이페이지 데이터 바인딩 작업

package-lock.json, src/apis/api.js, src/apis/auth.js, src/components/AuthGuard.jsx, src/pages/LoginPage.jsx, src/pages/MyPage.jsx, src/pages/MyPage.module.css, src/pages/SignUpPage.jsx, src/routes/index.jsx
- 로그인한 사용자만 접근할 수 있도록 AuthGuard 컴포넌트 적용
- 토큰 유효성 검사 및 userId 확인 로직 포함
- 인증 실패 시 /login 페이지로 리다이렉트 처리
=> 마이페이지 AuthGuard 적용

src/pages/MyPage.jsx, src/store/userSlice.js
=> Feat: 로그아웃 시, 데이터 전역 처리

src/components/Modal.jsx, src/components/Modal.module.css, src/pages/MyPage.jsx, src/pages/MyPage.module.css
- 모달 오픈 시 브라우저 스크롤 막기
- 모달 스크롤 시 모달 오른쪽 border-radius 깨짐 문제 해결
- 마이페이지 폰트체 수정
=> 마이페이지 리팩토링

package-lock.json, package.json, src/store/favoritesSlice.js
=> Feat:즐겨찾기 로직 수정

src/components/FloatingButton.module.css, src/components/Menu.module.css, src/components/Modal.module.css, src/index.css
- 모달 스크롤 바 커스텀 스타일링
- 플로팅 버튼 위치 수정 및 반응형 적용
- 하단바 오른쪽으로 밀리는 문제 수정
- html, body, #root 태그 기본 패딩 제거
=> 레이아웃 및 컴포넌트 스타일 수정

src/components/CatCard.jsx, src/components/Modal.module.css, src/pages/Home.jsx
=> Feat:최근 본 레시피 수정 및 디자인 수정

src/components/Comment.jsx
로그인 안하고 리뷰 작성 시 설정해놓은 alert안뜨던 부분 수정
=> Fix: 리뷰 작성 조건

src/pages/MyPage.jsx, src/pages/WithdrawPage.jsx
- 탈퇴 시, 전역 상태 업데이트
- 탈퇴 중 상태 관리
=> 회원탈퇴 로직 수정

src/components/Nutritional.jsx, src/components/Nutritional.module.css
=> 상세페이지 Progress bar 작업

README.md
=> README 화면 구성 내용 추가
